# Generated by Django 4.0 on 2021-12-30 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('postdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('excert', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='postimg/%Y/%m/%d')),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
                ('catpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
            ],
        ),
    ]
