# Generated by Django 4.0 on 2022-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_categoryname_category_catname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
    ]
